<?php

$namespaces = array();

$namespaces[] = array (
  '_id' => '504fb36cf311fed94d000008',
  'title' => 'MY: Metayogi',
  'prefix' => 'my',
  'url' => 'http://purl.org/my',
  'rdf:type' => 'my:namespaces',
);

$namespaces[] = array (
  '_id' => '50521ec4f311fefd7b000001',
  'title' => 'RDFS: RDF Schema',
  'prefix' => 'rdfs',
  'url' => 'http://purl.org/rdfs',
  'rdf:type' => 'my:namespaces',
);

$namespaces[] = array (
  '_id' => '50523e6cf311fee77b000001',
  'title' => 'RDF: Resource Description Framework',
  'prefix' => 'rdf',
  'url' => 'http://purl.org/rdf',
  'rdf:type' => 'my:namespaces',
);

$namespaces[] = array (
  '_id' => '505aabd30de4040a6800002c',
  'title' => 'XSD: XML Schema',
  'prefix' => 'xsd',
  'url' => 'http://www.w3.org/2001/XMLSchema',
  'rdf:type' => 'my:namespaces',
);

$namespaces[] = array (
  '_id' => '505ab54a0de4043e0a00000a',
  'title' => 'OWL: Web Ontology Language',
  'prefix' => 'owl',
  'url' => 'http://www.w3.org/2002/07/owl',
  'rdf:type' => 'my:namespaces',
);

/*
$namespaces[] = array (
  '_id' => '505ab4fd0de4040e6800002e',
  'title' => 'SKOS: Simple Knowledge Organization System',
  'prefix' => 'skos',
  'url' => 'http://www.w3.org/2004/02/skos/core',
  'rdf:type' => 'my:namespaces',
);

$namespaces[] = array (
  '_id' => '505d57d90de40407680000a2',
  'title' => 'FOAF: Friends of a Feather',
  'prefix' => 'foaf',
  'url' => 'http://xmlns.com/foaf/0.1/',
  'rdf:type' => 'my:namespaces',
);

$namespaces[] = array (
  '_id' => '505d58750de4040868000099',
  'title' => 'MADS: Metadata Authority Description',
  'prefix' => 'mads',
  'url' => 'http://www.loc.gov/mads/rdf',
  'rdf:type' => 'my:namespaces',
);

$namespaces[] = array (
  '_id' => '505d5de30de40407680000a3',
  'title' => 'MODS: Metadata Object Description',
  'prefix' => 'mods',
  'url' => 'http://www.loc.gov/mods/rdf',
  'rdf:type' => 'my:namespaces',
);

$namespaces[] = array (
  '_id' => '505d5ee80de404086800009a',
  'title' => 'METS: Metadata Encoding and Transmission Standard',
  'prefix' => 'mets',
  'url' => 'http://www.loc.gov/mets/rdf',
  'rdf:type' => 'my:namespaces',
);

*/
