<?php

/**
 * This file is part of Metayogi.
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

$sforms = array();

$sforms[] = array (
  '_id' => '524c7c0ef311fedb35461675',
  'advanced' => array (
    'advanced_fields' => '3',
    'advanced_indexes' => 
    array (
      0 => '524c7b6bf311fedd352ea788',
      1 => '524c7b90f311fedc35188812',
      2 => '524c7bb8f311feda35b0f111',
    ),
    'advanced_limits' => 
    array (
    ),
  ),
  'basic' => array (
    'basic_fields' => '1',
    'basic_indexes' => 
    array (
      0 => '524c7b6bf311fedd352ea788',
    ),
    'basic_limits' => 
    array (
    ),
  ),
  'controllerID' => '524c7c31f311fede35724063',
  'facets' => array (
  ),
  'label' => 'Admin Search',
  'layout' => '4eda94436c10ba3216000000',
  'name' => 'works',
  'rdf:type' => 'my:sforms',
);