<?php

/**
 * This file is part of Metayogi.
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

$classes = array();

$classes[] = array (
  '_id' => '52405fc2f311fef7182f13bf',
  'name' => 'work',
  'label' => 'Works',
  'comment' => '',
  'domain' => 'ssu',
  'abstract' => 0,
  'subclass' => array (
    '_id' => array (
      0 => '51a79a04f311fe4038000003',
      1 => '50c0f9f7f311fed270000056',
    ),
    '_ref' => 'rdfs:classes',
  ),
  'properties' => array (
    '_id' => array (
      0 => '52405f51f311fefe18db36e0',
      1 => '52405f7ef311fe0219f51670',
      2 => '52405fa0f311feff185e59f3',
      3 => '524c7992f311fed735bdb52d',
      4 => '524c79b8f311feda35a0254a',
    ),
    '_ref' => 'rdf:properties',
  ),
  'rdf:type' => 'rdfs:classes',
  'qname' => 'ssu:work',
);
