<?php

/**
 * This file is part of Metayogi.
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

 $work = array();
 
 $work[] = array (
  '_id' => '524d00e9f311feda35998455',
  'ssu:title' => 'Ulysses',
  'ssu:author' => 
  array (
    0 => 'James Joyce',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778367,
  'my:dateModified' => 1380778367,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d0182f311fedc35934ed2',
  'ssu:title' => 'The Great Gatsby',
  'ssu:author' => 
  array (
    0 => 'F. Scott Fitzgerald',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778423,
  'my:dateModified' => 1380778423,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d01baf311fed73575bfbf',
  'ssu:title' => 'Lolita',
  'ssu:author' => 
  array (
    0 => 'Vladimir Nabokov',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778452,
  'my:dateModified' => 1380778452,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d01e2f311fed93542b7ac',
  'ssu:title' => 'Brave New World',
  'ssu:author' => 
  array (
    0 => 'Aldous Huxley',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778478,
  'my:dateModified' => 1380778478,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d01f0f311fed8356af1e8',
  'ssu:title' => 'The Sound and the Fury',
  'ssu:author' => 
  array (
    0 => 'William Faulkner',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => '1380778511',
  'my:dateModified' => 1380778520,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d021bf311fedc35e79a52',
  'ssu:title' => 'Catch-22',
  'ssu:author' => 
  array (
    0 => 'Joseph Heller',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778548,
  'my:dateModified' => 1380778548,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d024ff311feda356ee1c9',
  'ssu:title' => '1984',
  'ssu:author' => 
  array (
    0 => 'George Orwell',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778589,
  'my:dateModified' => 1380778589,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d025ff311fedb3531892e',
  'ssu:title' => 'Animal Farm',
  'ssu:author' => 
  array (
    0 => 'George Orwell',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778609,
  'my:dateModified' => 1380778609,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d02acf311fedd35f160e7',
  'ssu:title' => 'Slaughterhouse-Five',
  'ssu:author' => 
  array (
    0 => 'Kurt Vonnegut',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778686,
  'my:dateModified' => 1380778686,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d02def311fede355cd318',
  'ssu:title' => 'Lord of the Flies',
  'ssu:author' => 
  array (
    0 => 'William Golding',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778730,
  'my:dateModified' => 1380778730,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d0307f311fedc35cba085',
  'ssu:title' => 'Pale Fire',
  'ssu:author' => 
  array (
    0 => 'Vladimir Nabokov',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778774,
  'my:dateModified' => 1380778774,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d031ff311fed735753261',
  'ssu:title' => 'Heart of Darkness',
  'ssu:author' => 
  array (
    0 => 'Joseph Conrad',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778822,
  'my:dateModified' => 1380778822,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d0381f311fedb3552b08c',
  'ssu:title' => 'Fahrenheit 451',
  'ssu:author' => 
  array (
    0 => 'Ray Bradbury',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778903,
  'my:dateModified' => 1380778903,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d03aaf311fedd3591ccbf',
  'ssu:title' => 'Naked Lunch',
  'ssu:author' => 
  array (
    0 => 'William S. Burroughs',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778944,
  'my:dateModified' => 1380778944,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d03ddf311fede35a4638f',
  'ssu:title' => 'The Call of the Wild',
  'ssu:author' => 
  array (
    0 => 'Jack London',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778988,
  'my:dateModified' => 1380778988,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d03edf311fedc35971af8',
  'ssu:title' => 'White Fang',
  'ssu:author' => 
  array (
    0 => 'Jack London',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380778999,
  'my:dateModified' => 1380778999,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d0415f311fed735e2a67f',
  'ssu:title' => 'A Clockwork Orange',
  'ssu:author' => 
  array (
    0 => 'Anthony Burgess',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380779044,
  'my:dateModified' => 1380779044,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d0432f311fed935f7e043',
  'ssu:title' => 'On the Beach',
  'ssu:author' => 
  array (
    0 => 'Nevil Shute',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380779071,
  'my:dateModified' => 1380779071,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d045ef311fed835aca5ef',
  'ssu:title' => 'Shane',
  'ssu:author' => 
  array (
    0 => 'Jack Schaefer',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380779111,
  'my:dateModified' => 1380779111,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d0480f311fedb35f3c4ad',
  'ssu:title' => 'The Catcher in the Rye',
  'ssu:author' => 
  array (
    0 => 'J.D. Salinger',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380779162,
  'my:dateModified' => 1380779162,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);

$work[] = array (
  '_id' => '524d04bff311fedd35f05dfd',
  'ssu:title' => 'A Town Like Alice',
  'ssu:author' => 
  array (
    0 => 'Nevil Shute',
  ),
  'ssu:summary' => '',
  'rdf:type' => 'ssu:work',
  'my:dateCreated' => 1380779214,
  'my:dateModified' => 1380779214,
  'my:live' => 1,
  'my:createdBy' => 'anonymous',
  'my:modifiedBy' => 'anonymous',
);