<?php

$regions = array();

$regions[] = array (
  '_id' => '4edadc506c10ba5a15030000',
  'name' => 'header',
  'blocks' => 
  array (
    '_id' => 
    array (
      0 => '50082228f311fee55400000a',
    ),
    '_ref' => 'my:blocks',
  ),
  'rdf:type' => 'my:regions',
);

$regions[] = array (
  '_id' => '4edadce36c10ba5915020000',
  'name' => 'footer',
  'blocks' => 
  array (
  ),
  'css' => 'background-color: #F5F5F5; height: 50px; ',
  'rdf:type' => 'my:regions',
);

$regions[] = array (
  '_id' => '4f5c575af311fe1f17000000',
  'name' => 'center',
  'classes' => 
  array (
    0 => 'container',
  ),
  'blocks' => 
  array (
  ),
  'rdf:type' => 'my:regions',
);