<?php

$controllers = array();

$controllers[] = array (
  '_id' => '4ebac9fe6c10ba4975000000',
  'label' => 'Menu',
  'name' => 'menu',
  'collection' => 'my:menus',
  'CRUDpath' => 'admin/menus',
  'actions' => array (
    'ListAction' => '4ec9edc96c10bae14b010000',
    'CreateAction' => '4ec9ee2b6c10badd5b000000',
    'EditAction' => '4ecddb8e6c10badb0a030000',
    'LoadAction' => '4ecddb4b6c10bada0a040000',
    'DeleteAction' => '4ecddb9d6c10bad90a020000',
  ),
  'rdf:type' => 'my:controllers',
);
